version: '3'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: express
      POSTGRES_PASSWORD: Assemblix86*
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../data:/var/lib/postgresql/data 
    expose:
      - "5432"