pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh 'cd api'
                sh 'ls'
                sh 'npm install'
                sh 'npm run dev'
            }
        }
    }
}